# Generated by Django 3.0.8 on 2020-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ponderacion',
            field=models.FloatField(default=0.0),
        ),
    ]
